
version: '3.0'
services:
  web:
    build: .
    # TODO: build context, ports and redis dependency
    ports:
      - "5000:5000"
    # TODO: image, ports and redis dependency
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc3
    volumes:
      - .:/data
    
    # TODO: persistence for redis. You need to persist /data directory.