
version: '3.0'
services:
  web:
    build: .
    # TODO: build context, ports and redis dependency
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      # Makes flask to reload code on change
      FLASK_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc4-alpine
    volumes:
      - .:/data
    #command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]
    # TODO: missing persistence for redis. You need to persist /data directory.

